# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpms', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpms.Room')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_homewtown', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_idcard', models.CharField(max_length=50)),
                ('user_company', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='room_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpms.User_info'),
        ),
    ]
