# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpms', '0004_charge_complaint_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('device_type', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Device_repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateField()),
                ('repair_content', models.CharField(max_length=128)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpms.Device')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='charge_complet',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='charge_cont',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_total',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='accident',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpms.Device'),
        ),
    ]
