# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpms', '0006_auto_20160423_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_user',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='room_user',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dpms.User_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Room_user',
        ),
    ]
