# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpms', '0008_auto_20160506_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
